spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:database/schema.sql
    data: classpath:database/data.sql
    sql-script-encoding: utf-8